words=[
    "apple",
    "attitude",
    "happy",
    "winner",
    "python",
    "example",
    "hangman",
    "problems",
    "terminal",
    "rakshitha",
    "learnings",
    "instagram",
    "facebook",
    "whatsapp",
    "debugging",
    "tuples"
]